Extensión SDK
mercadopago/sdk-nodejs pull request #140
Opened 2019-04-11 13:16 UTC by leitonet

Se incorporan modelos y servicios para soportar:

- Payment Methods
- Issuers
- Plans
- Subscritions
- Invoices

2019-04-13 03:48 UTC, joelibaceta commented
@leitonet si es un PR para el SDK por que seria necesario renombrar el paquete a `mercadopago-extended` ?

2019-04-13 19:52 UTC, leitonet commented
Hola Joel, no sería necesario cambiar el nombre.
Hacé un merge sólo de lo que consideren que represente un aporte.
Saludos

El sáb., 13 abr. 2019 12:48 AM, Joel Ibaceta <notifications@github.com>
escribió:

> @leitonet <https://github.com/leitonet> si es un PR para el SDK por que
> seria necesario renombrar el paquete a mercadopago-extended ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mercadopago/dx-nodejs/pull/140#issuecomment-482773236>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB32fZFging501dwIzC9BwhnBiraxEW8ks5vgVOMgaJpZM4cplc4>
> .
>

2019-04-15 18:27 UTC, joelibaceta commented on README.md
> +# MercadoPago-Extended Node.js SDK
```suggestion
# MercadoPago Node.js SDK
```

2019-04-15 18:28 UTC, joelibaceta commented on README.md
> +This library is an extension of "MercadoPago Node.js SDK", which provides developers with a simple set of bindings to the MercadoPago API. You can read the full [documentation here](https://github.co
```suggestion
This library provides developers with a simple set of bindings to the MercadoPago API. You can read the full [documentation here](https://github.com/mercadopago/px-nodejs/wiki).
```

2019-04-15 18:28 UTC, joelibaceta commented on README.md
> +This extension includes Payment Methods Issuers by bin, Plans, Subscritions and Invoices.
```suggestion
```

2019-04-15 18:28 UTC, joelibaceta commented on README.md
> +$ npm install mercadopago-extended
```suggestion
$ npm install mercadopago
```

2019-04-15 18:28 UTC, joelibaceta commented on README.md
> +$ npm install --save mercadopago-extended
```suggestion
$ npm install --save mercadopago
```

2019-04-15 18:29 UTC, joelibaceta commented on package.json
> +    "url": "git+https://github.com/leitonet/dx-nodejs.git"
```suggestion
    "url": "git+https://github.com/mercadopago/dx-nodejs.git"
```

2019-04-15 18:29 UTC, joelibaceta commented on package.json
> +    "url": "https://github.com/leitonet/dx-nodejs/issues"
```suggestion
    "url": "https://github.com/mercadopago/dx-nodejs/issues"
```

2019-04-15 18:29 UTC, joelibaceta commented on package.json
> +  "homepage": "https://github.com/leitonet/dx-nodejs#readme",
```suggestion
  "homepage": "https://github.com/mercadopago/dx-nodejs#readme",
```

2019-04-15 18:30 UTC, joelibaceta requested changes
- Mantener el nombre del paquete
-

2019-04-15 19:24 UTC, joelibaceta commented on lib/resources/customers.js
> +  path: '/v1/customers/search?email=:email',
Usar la firma generica 
```suggestion
  path: '/v1/customers/search',
```

2019-04-16 16:21 UTC, joelibaceta commented
@arielfr are you ok with this?

2019-04-24 13:53 UTC, arielfr commented on lib/resources/invoice.js
> +  idempotency: true
Hay que ver si esta API soporta idempotencia

2019-04-24 13:54 UTC, arielfr commented on lib/resources/payment.js
> +  path: '/v1/payment_methods/card_issuers?payment_method_id=:id&bin=:bin',
El Path debería ser: `/v1/payment_methods/card_issuers`. Los valores con `:valor` se utilizan para path variables.

Los query string se envían cuando se hace el llamado de esta forma:

```
var configurations = {
  qs: {
    'payer.id': 'me'
  }
};

mercadopago.payment.issuers(configurations, callback);
```

2019-04-24 13:54 UTC, joelibaceta commented on lib/resources/invoice.js
> +  idempotency: true
Me parece que no ya que solo se soportan peticiones GET

2019-04-24 13:55 UTC, arielfr requested changes
@joelibaceta Hay que corregir los puntos mencionados y agregar los tests. También habría que validar si los modelos son correctos mirando la API Reference

2021-01-11 23:51 UTC, ahsath commented
Hola, donde puedo encontrar documentacion para los metodos del cliente de nodejs? tambien tengo dos preguntas, el webhook para subscription es solo para cuando se hace la vinculacion de una cuenta? es decir cuando se llama a este endpoint: `https://api.mercadopago.com/preapproval`? y la segunda es, cuando un pago recurrente se ejecuta el tipo de notificacion del webhook es `payment` y el action es `payment.created` verdad?

2022-07-07 17:33 UTC, closed without merging