Feature/corech2 1300 add card token
mercadopago/sdk-nodejs pull request #251
Opened 2023-08-16 20:56 UTC by edmarSoaress

## Cambios realizados para el feature:
 * Implementação get CardToken 
* Implementação create CardToken 

Link do jira : https://mercadolibre.atlassian.net/browse/CORECH2-1300

2023-08-16 21:22 UTC, lucmkz requested changes

2023-08-16 21:22 UTC, lucmkz commented on examples/src/cardtoken/create/create.ts
> +    card_id : "9067121741",
remove esses exemplos 

deixa apenas ` card_id : "card_id",`

o mesmo para o CVV

2023-08-16 21:22 UTC, lucmkz commented on src/client/payments/search/index.ts
> +				'Authorization': `${config.accessToken}`
aqui ainda precisa do `bearer`, não podemos remover.

2023-08-17 12:23 UTC, edmarSoaress commented on src/client/payments/search/index.ts
> +				'Authorization': `${config.accessToken}`
Done!

2023-08-17 12:23 UTC, edmarSoaress commented on examples/src/cardtoken/create/create.ts
> +    card_id : "9067121741",
done!

2023-08-17 20:02 UTC, lucmkz approved these changes

2023-08-17 20:09 UTC, merged